language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install sphinx codespell
# command to run tests
script:
  # it is (currently) impossible to dismiss ignored suggestions but these are
  # still added to the exit code (which is a just a count of spelling
  # suggestions). Since we know we have one of these, we allow for that.
  # see https://github.com/easybuilders/easybuild/pull/485 for details
  - codespell --skip=".git,version-specific,scripts" --ignore-words-list=atleast,ninjs,simpy --quiet-level=2; retVal=$?; if [ $retVal -eq 1 ]; then echo "Got one expected warning, so success!";  else $(exit $retVal); fi;
  - READTHEDOCS=1 sphinx-build docs build
  # test installation too
  - pip install $TRAVIS_BUILD_DIR
  - eb --prefix /tmp/$USER bzip2-1.0.6.eb
