language: python
jobs:
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.8"
# command to install dependencies
install:
  - pip install sphinx codespell
# command to run tests
script:
  # it is (currently) impossible to dismiss ignored suggestions but these are
  # still added to the exit code (which is a just a count of spelling
  # suggestions). Since we know we have one of these, we allow for that.
  # see https://github.com/easybuilders/easybuild/pull/485 for details
  - codespell --skip=".git,version-specific,scripts" --ignore-words-list=atleast,ninjs,simpy,proovread --quiet-level=2; retVal=$?; if [ $retVal -eq 1 ]; then echo "Got one expected warning, so success!";  else $(exit $retVal); fi;
  - READTHEDOCS=1 sphinx-build docs build
  # test installation too (using options that don't require to have a modules tool installed)
  - pip install $TRAVIS_BUILD_DIR
  - eb --list-easyblocks | grep EB_bzip2
  - eb --fetch bzip2-1.0.6.eb
