name: Check URLs

on: [push, pull_request]
jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - name: URLs-checker
      uses: SuperKogito/URLs-checker@0.1.3
      with:
        # The project base path.
        git_path: https://github.com/easybuilders/easybuild

        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.rst,.sh

        # Choose whether to include file with no URLs in the prints.
        print_all: False
